# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vessl < Formula
  desc "A powerful command-line interface for managing Docker containers"
  homepage "https://github.com/saswatsam786/vessl"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Darwin_x86_64.tar.gz"
      sha256 "b66d9f512419e25e4e236f01101db1b0e11774f1cf37e8d11de57868b325da54"

      def install
        bin.install "vessl"
      end
    end
    on_arm do
      url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Darwin_arm64.tar.gz"
      sha256 "e08a40be81b346391788a3a550ec00cd7949f47eefcf5d0620d3b53240c543ea"

      def install
        bin.install "vessl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Linux_x86_64.tar.gz"
        sha256 "f574079533fc2121621f5876c8815babdc5f4f2583d0a5f041d967424d096ab7"

        def install
          bin.install "vessl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Linux_arm64.tar.gz"
        sha256 "730fdb2bffdeef8008c453e32721a0b5cebe8ba9d213e8ecc6cf971d39f25e6e"

        def install
          bin.install "vessl"
        end
      end
    end
  end
end
