# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vessl < Formula
  desc "A powerful command-line interface for managing Docker containers"
  homepage "https://github.com/saswatsam786/vessl"
  version "1.0.7-next"

  on_macos do
    on_intel do
      url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Darwin_x86_64.tar.gz"
      sha256 "f6360d738e9ee0222135161b7d14eaec22d86e4f79d3a054ba24d05b464aa550"

      def install
        bin.install "vessl"
      end
    end
    on_arm do
      url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Darwin_arm64.tar.gz"
      sha256 "e08a40be81b346391788a3a550ec00cd7949f47eefcf5d0620d3b53240c543ea"

      def install
        bin.install "vessl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Linux_x86_64.tar.gz"
        sha256 "c3e1eadfcf4691b38ff9a370e398ac068cad3172539c5cebc0e951d0c4825d4c"

        def install
          bin.install "vessl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saswatsam786/vessl/releases/download/v1.0.6/vessl_Linux_arm64.tar.gz"
        sha256 "6cbfdb28a281b9e68039ffe5a0f7cacef604db361b3a800edd1072f6786733e1"

        def install
          bin.install "vessl"
        end
      end
    end
  end
end
