name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/vessl-linux-amd64
            build/vessl-darwin-amd64
            build/vessl-darwin-arm64
            build/vessl-windows-amd64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 